Github actions and other fixes

diff --git a/Tunnel Client/examples/Github Actions/superprotocol-test-app-tunnel-server.yml b/Tunnel Client/examples/Github Actions/superprotocol-test-app-tunnel-server.yml
--- a/Tunnel Client/examples/Github Actions/superprotocol-test-app-tunnel-server.yml
+++ b/Tunnel Client/examples/Github Actions/superprotocol-test-app-tunnel-server.yml
@@ -20,6 +20,19 @@ jobs:
       repository-projects: read
 
     steps:
+      - name: Check secrets and variables
+        run: |
+          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
+            echo "Error: GH_TOKEN secret is missing. Workflow will fail."
+            exit 1
+          elif [ -z "${{ secrets.SOLUTION_SERVER_TOKEN }}" ]; then 
+            echo "Error: SOLUTION_SERVER_TOKEN secret is missing. Workflow will fail."
+            exit 1
+          elif [ -z "${{ secrets.SPCTL_CONFIG_BASE64 }}" ]; then 
+            echo "Error: SPCTL_CONFIG_BASE64 secret is missing. Workflow will fail."
+            exit 1
+          fi
+
       - name: Get previous build for solution
         continue-on-error: true
         env:
@@ -72,7 +85,7 @@ jobs:
             fi
           fi
 
-          ./spctl workflows create --tee 1 --solution ${{ env.BASE_IMAGE_OFFER }} --solution ${{ env.TUNNEL_SERVER_OFFER  }} --data ${{ env.SOLUTION_DATA_FILE }} --storage ${{ env.STORAGE_OFFER }} --orders-limit 10000 > workflow_result.txt
+          ./spctl workflows create --tee 1 --solution ${{ env.BASE_IMAGE_OFFER }} --solution ${{ env.TUNNEL_SERVER_OFFER  }} --data ${{ env.SOLUTION_DATA_FILE }} --storage ${{ env.STORAGE_OFFER }} --orders-limit 10000 --min-rent-minutes 60 > workflow_result.txt
 
           cat workflow_result.txt
 
