feat(comfyui): ComfyUI added

diff --git a/.github/workflows/build-engine.yml b/.github/workflows/build-engine.yml
--- a/.github/workflows/build-engine.yml
+++ b/.github/workflows/build-engine.yml
@@ -1,8 +1,14 @@
-name: Build Text Generation WebUI Solution
+name: Build Engine
 
 on:
   workflow_dispatch:
     inputs:
+      solution:
+        required: true
+        type: choice
+        options:
+          - text-generation-webui
+          - comfyui
       target:
         description: 'Target'
         required: true
@@ -15,10 +21,11 @@ on:
 env:
   IMAGE_FILE: ''
   IMAGE_RESOURCE: ''
-  SOLUTION: text-generation-webui
+  SOLUTION: ${{ inputs.solution }}
   PR_REPO_ARGO: super-protocol/argocd-clusters
   DOCKERFILE: "./Text\ Generation\ WebUI/Dockerfile"
   DOCKERFILE_CONTEXT: "./Text\ Generation\ WebUI/"
+  SUBMODULE_PATH: ''
   TARGET: ${{ inputs.target }}
 
 jobs:
@@ -33,9 +40,28 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Prepare variables
+        run: |
+          if [ "$SOLUTION" == "text-generation-webui" ]; then
+            DOCKERFILE="./Text\ Generation\ WebUI/Dockerfile"
+            DOCKERFILE_CONTEXT="./Text\ Generation\ WebUI/"
+            SUBMODULE_PATH="Text\ Generation\ WebUI/text-generation-webui"
+          elif [ "$INSTANCE" == "comfyui" ]; then
+            DOCKERFILE="./ComfyUI/Dockerfile"
+            DOCKERFILE_CONTEXT="./ComfyUI/"
+            SUBMODULE_PATH="ComfyUI/ComfyUI"
+          else
+            echo "Invalid solution name"
+            exit 1
+          fi
+
+          echo "DOCKERFILE=$DOCKERFILE" >> $GITHUB_ENV
+          echo "DOCKERFILE_CONTEXT=$DOCKERFILE_CONTEXT" >> $GITHUB_ENV
+          echo "SUBMODULE_PATH=$SUBMODULE_PATH" >> $GITHUB_ENV
+
       - name: Checkout git submodules
         run: |
-          git submodule init && git submodule update
+          git submodule init && git submodule update $SUBMODULE_PATH
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
