feat(Text Generation WebUI): support solution configuration (SP-4986) (#58)
* fix(generate-config-schema-from-csv): type and variable existence check

* fix(generate-config-schema-from-csv): Check variable for every item

* initial commit

* feat(Text Generation WebUI): add parseTunnelProvisionerOrderResult helper (SP-4986)

* feat(Text Generation WebUI):  support tunnelConfig in getTunnelClientConfig (SP-4986)

* fix(Text Generation WebUI): fix getTunnelClientConfig (SP-4986)

* refactor(Text Generation WebUI): remove duplicated getEnvValueOrFail (SP-4986)

* fix(Text Generation WebUI): fix types (SP-4986)

* feat(Text Generation WebUI): use tunnelClientConfig from ConfigurationParser (SP-4986)

* chores: added logs + minor changes

* added envs to dockerfile

* fix: order encryption key compatibility

* fix(Text Generation WebUI): remove circular dependencies (SP-4986)

* refactor(Text Generation WebUI): implement findConfigInConfiguration (SP-4986)

* refactor(Text Generation WebUI): findConfigInConfiguration->getDomainConfigByConfiguration (SP-4986)

* refactor(Text Generation WebUI): implement solution-configuration (SP-4986)

* fix(Text Generation WebUI): implement getServerConfig (SP-4986)

* fix: added fake mrenclave and mrsigner

* feat(Text Generation WebUI): wait for tunnel provisioner order result (SP-4986)

* chore(deps): upgrade @super-protocol/dto-js to 0.1.11 and @super-protocol/sdk-js to 2.2.0-beta.112

* refactor(Text Generation WebUI): remove redundant comments (SP-4986)

* ci(Text Generation WebUI): add "Create .env file" step

* chore(Text Generation WebUI): remove env vars

* ci(Text Generation WebUI):  debug .env file

* chore(Text Generation WebUI): remove debug  log from Dockerfile

* chore(Text Generation WebUI): update .env.example

---------

Co-authored-by: Vlad Marchuk <marchukvl02@gmail.com>
Co-authored-by: Dmitry Somov <smv.dmitry@gmail.com>

diff --git a/.github/workflows/text-generation-webui-build.yml b/.github/workflows/text-generation-webui-build.yml
--- a/.github/workflows/text-generation-webui-build.yml
+++ b/.github/workflows/text-generation-webui-build.yml
@@ -44,6 +44,20 @@ jobs:
           driver-opts: |
             image=moby/buildkit:v0.12.0
 
+      - name: Create .env file
+        run: |
+          cd "$DOCKERFILE_CONTEXT"
+
+          if [ "$TARGET" == "develop" ]; then
+            echo "${{ secrets.DEV_TGWUI_ENV_BASE64 }}" | base64 --decode > .env
+          elif [ "$TARGET" == "stage" ]; then
+            echo "${{ secrets.STG_TGWUI_ENV_BASE64 }}" | base64 --decode > .env
+          elif [ "$TARGET" == "testnet" ]; then
+            echo "${{ secrets.TESTNET_TGWUI_ENV_BASE64 }}" | base64 --decode > .env
+          else
+            echo "Invalid instance: $TARGET"
+            exit 1
+          fi
       - name: Build Docker image and save to file
         run: |
           IMAGE_FILE="$SOLUTION-image-b${{ github.run_id }}.tar.gz"
